Nepa_Project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('', include('Nepa_application.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),

]
urlpatterns+=staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Nepa_application/models.py
from django.db import models
from django.core.validators import EmailValidator
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

# creating a model for 7 provience that contains name, capital description and image using cloudinary


class province(models.Model):
    name = models.CharField(max_length=100)
    capital = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='Provience_Image/')

    def __str__(self):
        return self.name

class image(models.Model):
    image = models.ImageField(upload_to='all_image/')
    provience = models.ForeignKey(province, on_delete=models.CASCADE, related_name = 'images')
  
    

class Contact_us(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(validators=[EmailValidator(message='Enter a valid email address.')])
    phone = models.CharField(max_length=10)  # Adjust length as needed
    text_message = models.TextField()
    post_date = models.DateTimeField(default=timezone.now, null=True, blank=True)

    class Meta:
        ordering = ['-post_date']
    

class Topic(models.Model):
    title = models.CharField(max_length=100)
    long_description = models.TextField()
    category = models.ManyToManyField("Category", related_name='topics')
    province = models.ForeignKey(province, on_delete=models.CASCADE, related_name='topics')
    post_date = models.DateTimeField(default=timezone.now)
    is_verified = models.BooleanField(default=False)
    author = models.CharField(max_length=100, default="Anonymous")
    likes = models.ManyToManyField(User, related_name='topic', blank=True)
    report = models.IntegerField(User, default=0)
    commentCount = models.IntegerField(default=0, null=True, blank=True)
    views = models.IntegerField(default=0)


    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-post_date']
    
    def total_likes(self):
        return self.likes.count()
    
class Report_Post(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    

    class Meta:
        unique_together = ('topic', 'user')

class T_Image(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='topic_images')

class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='category_images')

    def __str__(self):
        return self.name

class Comment(models.Model):
   author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commenter")
   content = models.TextField()
   post = models.ForeignKey(Topic, on_delete=models.CASCADE, default=None, null=True, blank=True
   )
   postedOn = models.DateTimeField(auto_now=True, blank=True)


   class Meta:
       ordering = ["-postedOn"]


   def __str__(self):
       return f"{self.content}"

templates/admin_contacts.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Tooplate">
  <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
  <title>NEPASHRAY</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/owl-carousel.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/tooplate-artxibition.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <link href="{% static 'assets/css/main.css' %}" rel="stylesheet" />
  <style>
     .sidebar {
        margin: 0;
        padding: 0;
        width: 200px;
        background-color: #f1f1f1;
        position: fixed;
        height: 100%;
        overflow: auto;
      }
      
      .sidebar a {
        display: block;
        color: black;
        padding: 16px;
        text-decoration: none;
      }
       
      .sidebar a.active {
        background-color: #04AA6D;
        color: white;
      }
      
      .sidebar a:hover:not(.active) {
        background-color: #555;
        color: white;
      }
      
      div.content {
        margin-left: 200px;
        padding: 1px 16px;
        height: 1000px;
      }
      
      @media screen and (max-width: 700px) {
        .sidebar {
          width: 100%;
          height: auto;
          position: relative;
        }
        .sidebar a {float: left;}
        div.content {margin-left: 0;}
      }
      
      @media screen and (max-width: 400px) {
        .sidebar a {
          text-align: center;
          float: none;
        }
      }
  </style>
</head>
<body>
  
<header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <a href="{% url 'index' %}" class="logo">NEP<em>आश्रय</em></a>
                    <ul class="nav">
                        {% if user.is_authenticated %}
                        <button class="contactbutton" style="margin-left: 10px;"> <a href="{% url 'signout' %}"">Log out <i class="fa fa-arrow-right"></i></a></button>
                        {% endif %}
                    </ul>        
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                </nav>
            </div>
        </div>
    </div>
</header>
<div class="sidebar">
    <a  href="{%url 'upload'%}">Dashboard</a>
    {% if user.is_authenticated and user.is_staff %}
    <a href="{% url 'manage_user'  %}">Manage Users</a>
    <a href="{% url 'admin_contacts'%}" id = "refreshButton" class="active">Contacts</a>
    <a href="{% url 'create_post' %}">Create a Post</a>
    <a href="{% url 'listofpost' %}">View post</a>

    <script>
        document.getElementById("refreshButton").addEventListener("click", function() {
            location.reload();  // Reload the current page
        });
    </script>

    {% elif user.is_authenticated and not user.is_staff %}
    <a href="{% url 'create_post' %}">Create a Post</a>
    <a href="{% url 'listofpost' %}">View post</a>


    {% endif %}
    <a href="{% url 'signout' %}">Logout</a>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Phone Number</th>
                        <th>Message</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in contacts %}
                    <tr>
                        <td>{{ user.name }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.phone }}</td>
                        <td>{{ user.text_message }}</td>
                        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="assets/js/jquery-2.1.0.min.js"></script>
<script src="assets/js/popper.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/js/scrollreveal.min.js"></script>
<script src="assets/js/waypoints.min.js"></script>
<script src="assets/js/jquery.counterup.min.js"></script>
<script src="assets/js/imgfix.min.js"></script> 
<script src="assets/js/mixitup.js"></script> 
<script src="assets/js/accordions.js"></script>
<script src="assets/js/owl-carousel.js"></script>
<script src="assets/js/custom.js"></script>
</body>
</html>

templates/contactpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'assets/css/contact.css' %}">
</head>
<body>

    <form id="contactForm" action="{% url 'contact' %}" method ="POST"> 
        {% csrf_token %}

        <div class="background">
            <div class="containerofcontact">
            <div class="screen">
                <div class="screen-header">
                <div class="screen-header-left">
                    <div class="screen-header-button close"></div>
                    <div class="screen-header-button maximize"></div>
                    <div class="screen-header-button minimize"></div>
                </div>
                <div class="screen-header-right">
                    <div class="screen-header-ellipsis"></div>
                    <div class="screen-header-ellipsis"></div>
                    <div class="screen-header-ellipsis"></div>
                </div>
                </div>
                <div class="screen-body">
                <div class="screen-body-item left">
                    <div class="app-title">
                    <span >Yay,</span><br>
                    <span>we're super eager to receive your messages and feedbacks!</span>
                    </div><br>
                    <div class="app-contact">CONTACT INFO : www.nepashray@gmail.com</div>
                </div>
                <div class="screen-body-item">
                    <div class="app-form">
                    <div class="app-form-group">
                        <input class="app-form-control" name="name" placeholder="NAME" >
                    </div>
                    <div class="app-form-group">
                        <input class="app-form-control" name= "email"placeholder="EMAIL">
                    </div>
                    <div class="app-form-group">
                        <input class="app-form-control" name= "phone"placeholder="CONTACT NO">
                    </div>
                    <div class="app-form-group message">
                        <input class="app-form-control" name= "text_message"placeholder="MESSAGE">
                    </div>
                    <div class="app-form-group buttons">
                        <button id="cancelButton" class="app-form-button"><a href="{% url 'index' %}" style="text-decoration: none; color: inherit;">CANCEL</a></button>
                        <button type="submit" class="app-form-button">SEND</button>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            </div>
        </div>
    </form>

    
</body>
</html>

templates/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Tooplate">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">

    <title>ART & CULTURAL</title>

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/owl-carousel.css' %}">

    <link rel="stylesheet" href="{% static 'assets/css/tooplate-artxibition.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

<!-- this later added -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400" rel="stylesheet" />
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet" />


    </head>
    
    <body>


        
    <!-- ***** Pre HEader ***** -->
    <!-- <div class="pre-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-sm-6">
                    <span>Namaste to Our StoryTeller/Seeker!</span>
                </div>
                <div class="col-lg-6 col-sm-6">
                    <div class="text-button">
                       <button class="contactbutton"> <a href="contactpage.html">Contact Now <i class="fa fa-arrow-right"></i></a></button>
                    </div>
                </div>
            </div>
        </div>
    </div> -->
    {% if messages %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endif %}
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="{% url 'create_post' %}">CREATE NEW POST HERE</a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li><a href="{% url 'index' %}" class="active">Home</a></li>
                            <!-- <li><a href="#about">About Us</a></li> -->
                            <!-- need to change upper amazing venues to about us here and below later -->

                            <li><a href="#post">See Posts</a></li>
                            <!-- <li><a href="discovernew.html">Discover More</a></li> -->

                            <li><a href="{% url 'contact' %}">Contact</a></li>

                            <!-- <li><a href="tickets.html">Tickets</a></li>  -->
                        </ul>        
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->


    <!-- ***** er Area Start ***** -->
    <div class="main-banner" style="background-image: linear-gradient(rgba(33, 8, 96, 0.974), rgba(39, 241, 224, 0.229)), url('{% static "assets/images/art.jpg" %}')">

        <!-- url(assets/images/art.jpg) -->
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="main-content">
                        
                        <h5 class="add-white">Hey, Seems Like You're Interested In Our Artists!</h5>
                        <h2> LOOK AT OUR ARTSY CREATIVE GEEKS</h2>
                        <div class="main-white-button">
                            <!-- <input type="text" id="input-box" placeholder="Anything specific ?, Let us know the keyword"> -->
                            <!-- <button>SEARCH</button> -->
<!--                            <a href="{% url 'create_topic' %}">CREATE NEW POST HERE</a> -->
                          <a href="{% url 'create_post' %}">CREATE NEW POST HERE</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Main Banner Area End ***** -->

    <!-- *** Owl Carousel Items ***-->
    <div class="show-events-carousel">
        <div class="container">
            <div class="row">
                <div id="post"
                <div class="col-lg-12">
                    <div class="owl-show-events owl-carousel">
                        <div class="item">
                            <a href="event-details.html"><img class="img-fit" src="assets/images/carousellimg1.jpg" alt=""></a>
                        </div>
                        <div class="item">
                            <a href="event-details.html"><img class="img-fit" src="assets/images/carousellimg3.jpg" alt=""></a> 
                        </div>
                        <div class="item">
                            <a href="event-details.html"><img class="img-fit" src="assets/images/carousellimg2.jpg" alt=""></a> 
                        </div>
                        <div class="item">
                            <a href="event-details.html"><img class="img-fit" src="assets/images/carousellimg5.jpg" alt=""></a> 
                        </div>
                        <div class="item">
                            <a href="event-details.html"><img class="img-fit" src="assets/images/carousellimg1.jpg" alt=""></a> 
                        </div>
                        <div class="item">
                            <a href="event-details.html"><img class="img-fit" src="assets/images/shrayimg5.jpg" alt=""></a> 
                        </div>
                        <div class="item">
                            <a href="event-details.html"><img class="img-fit" src="assets/images/carousellimg2.jpg" alt=""></a> 
                        </div>
                        <div class="item">
                            <a href="event-details.html"><img class="img-fit" src="assets/images/carousellimg5.jpg" alt=""></a> 
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- ART POSTS SHOWCASE -->

    <!-- latest postss nepashray -->
    <div id="latests">
        <div class="venue-tickets"> 
            <div class="container-fluid">
               <div class="row">
                   <div class="col-lg-12">
                       <div class="section-heading">
                           <h2>RELEVANT POSTS</h2>
                       </div>
                   </div>
                   <div class="col-lg-4">
                       <div class="venue-item">
                           <div class="thumb">
                               <img src="{% static 'assets/images/skatee.jpg' %}" alt="">
                           </div>
                           <div class="down-content">
                               <div class="left-content">
                                   <div class="main-white-button">
                                       <a href="viewpage.html">VIEW</a>
                                   </div>
                               </div>
                               <div class="right-content">
                                   
                                   <h4>SKATEBOARDERS OF NEPAL</h4>
                                   <div class="price">
                                       <span>posted<br>by <b>Ronish Dahal</b></span>
                                   </div>
   
                                   <p>See Story of the Skate Jatra Event that happened in Butwal, Nepal on 15th January,2024.
                                   <ul>
                                       <li><i class="fa fa-thumbs-up"></i>250</li>
                                       <li><i class="fa fa-eye"></i>500</li>
                                   </ul>
                               </div> 
                           </div>
                       </div>
                   </div>
   
                   <div class="col-lg-4">
                       <div class="venue-item">
                           <div class="thumb">
                               <img src="{% static 'assets/images/embroidery.jpg' %}" alt="">
                           </div>
                           <div class="down-content">
                               <div class="left-content">
                                   <div class="main-white-button">
                                       <a href="viewpage.html">VIEW</a>
                                   </div>
                               </div>
                               <div class="right-content">
                                   
                                   <h4>EMBROIDERY CRAFT</h4>
                                   <div class="price">
                                       <span>posted<br>by <b>Avilasha Malla</b></span>
                                   </div>
   
                                   <p>Amidst Himalayas, in Solukhumbu Region, people practice crafts for creative expression.</p>
                                   <ul>
                                       <li><i class="fa fa-thumbs-up"></i>270</li>
                                       <li><i class="fa fa-eye"></i>400</li>
                                   </ul>
                                   <!-- <div class="price">
                                       <span>1 ticket<br>from <em>$45</em></span>
                                   </div> -->
                               </div> 
                           </div>
                       </div>
                   </div>
   
                   <div class="col-lg-4">
                       <div class="venue-item">
                           <div class="thumb">
                               <img class="image-contain" src="{% static 'assets/images/sarrr.jpg'%}" alt="">
                           </div>
                           <div class="down-content">
                               <div class="left-content">
                                   <div class="main-white-button">
                                       <a href="viewpage.html">VIEW</a>
                                       <!-- mathiko view need to change link -->
                                   </div>
                               </div>
                               <div class="right-content">
                                   
                                   <h4>SARANGI KA DHUN</h4>
                                   <div class="price">
                                       <span>posted<br>by <b>Yunesh Gandarva</b></span>
                                   </div>
   
                                   <p>The soothing nepali folk music! Join Yunesh and have a delightful musical experience for a good mood!</p>
                                   <ul>
                                       <li><i class="fa fa-thumbs-up"></i>280</li>
                                       <li><i class="fa fa-eye"></i>500</li>
                                   </ul>
                                   <!-- <div class="price">
                                       <span>1 ticket<br>from <em>$45</em></span>
                                   </div> -->
                               </div> 
                           </div>
                       </div>
                   </div>
                   
                </div>
           </div>
        </div>       

    </body>

</html>

templates/create_topic.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Create Topic</title>
    <style>
        /* Retain existing CSS and add more styles */

        /* Additional styles for form */
        body {
            font-family: Arial, sans-serif;
            /* background-color: #d61b1b; */
            margin: 0;
            padding: 0;
        }
        h2 {
            color: #333;
            text-align: center;
            margin-top: 20px;
        }
        form {
            max-width: 400px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        label {
            display: block;
            margin-bottom: 10px;
            color: #555;
        }
        input[type="text"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }
        input[type="file"] {
            margin-bottom: 20px;
        }
        button[type="submit"] {
            background-color: #4CAF50;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }
        button[type="submit"]:hover {
            background-color: #45a049;
        }
        /* adding padding to the form and text field*/
        form {
            padding: 50px;
        }
    </style>
</head>
<body>
    {% if messages %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endif %}
    <h2 style="margin-top: 100px;">Hello {{ username }}</h2>
    <div>
        <form method="post" enctype="multipart/form-data" style="margin-top: 50px; box-shadow: #000000;">
            {% csrf_token %}
            <h2 style="margin-bottom: 20px; text-align: center;">Create Topic</h2>
            {{ form.as_p }}
            <input type="file" name="images" multiple style="margin-bottom: 20px; width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 3px;">
            <button type="submit" style="background-color: #4CAF50; color: #fff; padding: 10px 20px; border: none; border-radius: 3px; cursor: pointer; width: 100%;">Submit</button>
        </form>
    </div>
</body>
</html>

templates/listofpost.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

 <head>

   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <meta name="description" content="">
   <meta name="author" content="Tooplate">
   <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">

   <title>NEPASHRAY</title>


   <!-- Additional CSS Files -->
   <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">

   <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.css' %}">

   <link rel="stylesheet" type="text/css" href="{% static 'assets/css/owl-carousel.css' %}">

   <link rel="stylesheet" href="{% static 'assets/css/tooplate-artxibition.css' %}">
   <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

<!-- this later added -->
   <link href="https://fonts.googleapis.com/css?family=Poppins:300,400" rel="stylesheet" />
   <link href="{% static 'assets/css/main.css' %}" rel="stylesheet" />


   </head>
   
   <body>
       
   <!-- ***** Preloader Start ***** -->
   <!-- <div id="js-preloader" class="js-preloader">
     <div class="preloader-inner">
       <span class="dot"></span>
       <div class="dots">
         <span></span>
         <span></span>
         <span></span>
       </div>
     </div>    
   </div> -->
   <!-- ***** Preloader End ***** -->
   
   <!-- ***** Pre HEader ***** -->
   <div class="pre-header">
       <div class="container">
           <div class="row">
               <div class="col-lg-6 col-sm-6">
                   <span>Namaste to Our StoryTeller/Seeker!</span>
               </div>
               <div class="col-lg-6 col-sm-6">
                   <div class="text-button">
                      <button class="contactbutton"> <a href="{% url 'contact' %}">Contact Now <i class="fa fa-arrow-right"></i></a></button>
                      {% if user.is_authenticated %}
                      <button class="contactbutton" style="margin-left: 10px;"> <a href="{% url 'signout' %}"">Log out <i class="fa fa-arrow-right"></i></a></button>
                      {% endif %}
                   </div>
               </div>
           </div>
       </div>
   </div>
   
   <!-- ***** Header Area Start ***** -->
   <header class="header-area header-sticky">
       <div class="container">
           <div class="row">
               <div class="col-12">
                   <nav class="main-nav">
                       <!-- ***** Logo Start ***** -->
                       <a href="{% url 'index' %}" class="logo">NEP<em>आश्रय</em></a>
                       <!-- ***** Logo End ***** -->
                       <!-- ***** Menu Start ***** -->
                       <ul class="nav">
                           <li><a href="{% url 'index' %}">Home</a></li>
                           <li><a href="#">Watch</a></li>
                           <li><a href="{% url 'upload' %}">Dashboard</a></li>
                           <!-- <li>Upload</li> -->

                           <!-- <li><a href="{% url 'authregister' %}">Register</a></li> -->
                       
                           <!-- <li><a href="{% url 'authregister' %}">Register</a></li>  -->
                           <!-- <li><a href="tickets.html">Tickets</a></li>  -->
                       </ul>        
                       <!-- ***** Menu End ***** -->
                   </nav>
               </div>
           </div>
       </div>
   </header>
<div class="row">
 {% for post in posts %}
 {% if post.is_verified %}
 <div class="col-lg-4">
   <div class="venue-item" style="margin-bottom: 30px;">
     {% for image in post.t_image_set.all %}
     <div class="thumb" style="object-fit: cover; height: 350px;">
       <img src="{{ image.image.url }}" alt="{{post.title}}" />
     </div>
     {% endfor %}
     <div class="down-content"style="height: 450px;">
       <div class="left-content">
         <div class="main-white-button">
           <a href="{% url 'detailed_view' post.id %}">VIEW</a>
         </div>
       </div>
       <div class="right-content" style="height: 350px;">
         <h4>{{ post.title.title| slice:50 }}</h4>
         <div class="price">
           <span>posted<br>by <b> {{post.author.title}}</b></span>
       </div>
         <p style="margin-top: 0px;">{{ post.long_description | slice:"200" }}</p>
         <ul>
           <li><i class="fa fa-thumbs-up"></i>{{post.total_likes}}</li>
           <li><i class="fa fa-eye"></i>{{post.views}}</li>
         </ul>
       </div>
     </div>
   </div>
 </div>
 {% endif %}
 {% endfor %}
</div>